config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "events#index"

  resources :events do
    resources :comments, only: %i[ create destroy ]
    resources :subscriptions, only: %i[ create destroy ]
    resources :photos, only: %i[ create destroy ]
    post :show, on: :member
  end

  resources :users, only: %i[ show edit update destroy ]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user
  has_many :photos, dependent: :destroy

  validates :title, presence: true, length: {maximum: 255}
  validates :address, presence: true
  validates :datetime, presence: true

  def visitors
    (subscribers + [user]).uniq
  end

  def pincode_valid?(pin2chek)
    pincode == pin2chek
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[ show index ]
  before_action :set_event, except: %i[ index new create ]
  after_action :verify_authorized, except: %i[ index new ]
  after_action :verify_policy_scoped, only: :index

  def index
    @events = policy_scope(Event)
  end

  def show
    if params[:pincode].present? && @event.pincode_valid?(params[:pincode])
      cookies.permanent["events_#{@event.id}_pincode"] = params[:pincode]
    end

    authorize @event

    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    @new_photo = @event.photos.build(params[:photo])
  rescue Pundit::NotAuthorizedError
    flash.now[:alert] = t('pundit.incorrect_event_pincode') if params[:pincode].present?
    render 'password_form'
  end

  def new
    @event = current_user.events.build
  end

  def edit
    authorize @event
  end

  def create
    @event = current_user.events.build(event_params)
    authorize @event

    if @event.save
      redirect_to @event, notice: I18n.t('controllers.events.created')
    else
      render :new
    end
  end

  def update
    authorize @event
    if @event.update(event_params)
      redirect_to @event, notice: I18n.t('controllers.events.updated')
    else
      render :edit
    end
  end

  def destroy
    authorize @event
    @event.destroy
    redirect_to events_url, notice: I18n.t('controllers.events.destroyed')
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :address, :datetime, :description, :pincode)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_edit_form.html.erb
<%= form_for(@event) do |f| %>
  <%= render partial: 'partials/form_errors', locals: { model: @event } %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :datetime %>
    <p><%= f.datetime_select :datetime, class: 'form-control' %></p>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :pincode %>
    <%= f.text_field :pincode, class: 'form-control' %>
  </div>

  <br/>

  <div class="actions">
    <%= f.submit t('button.save'), class: 'btn btn-primary' %>
    или <%= link_to t('button.back'), :back %>
  </div>
<% end %>

<div class="delete-event">
  <%= link_to t('titles.delete_event'), @event, method: :delete,
    data: { confirm: t('titles.confirm_before_delete') },
    class: 'delete-event-link' %>
</div>

app/views/events/_event.html.erb
<div class="col-sm-6 col-md-4 event-window">
  <div class="thumbnail">

    <%= content_tag 'div', '', class: 'event-background',
      style: "background-image: url(#{event_photo(event)})" %>

    <div class="thumbnail-inner event-info-inner">
      <div class="caption">
        <div class="event-description">
          <h3><%= link_to event.title, event_path(event) %></h3>
          <h3>
            <small><%= l event.datetime, format: :short %></small>
          </h3>
          <div class="buffer-both"><%= event.address %></div>
        </div>
      </div>
      <% event.visitors.each do |user| %>
        <%= image_tag user_avatar_thumb(user), class: 'img-icon', title: user.name %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: @event} %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :datetime %>
    <p><%= f.datetime_select :datetime, class: 'form-control' %></p>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit words_translate('button.save'), class: 'btn btn-primary' %>
    или <%= link_to words_translate('button.back'), :back %>
  </div>
<% end %>

app/views/events/_new_form.html.erb
<%= form_for(@event) do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: @event} %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :datetime %>
    <p><%= f.datetime_select :datetime, class: 'form-control' %></p>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :pincode %>
    <%= f.text_field :pincode, class: 'form-control' %>
  </div>

  <br/>

  <div class="actions">
    <%= f.submit t('button.save'), class: 'btn btn-primary' %>
    или <%= link_to t('button.back'), :back %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1><%= t 'titles.edit_event' %></h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'edit_form' %>
  </div>
</div>

app/views/events/index.html.erb
<h1><%= t 'titles.events' %></h1>

<div class="buffer-both">
  <%= link_to t('button.create_event'), new_event_path, class: 'btn btn-success' %>
</div>

<div class="row buffer-bottom">
  <%= render partial: 'events/event', collection: @events %>
</div>

app/views/events/new.html.erb
<h1><%= t 'titles.new_event' %></h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'new_form' %>
  </div>
</div>

app/views/events/password_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col col-md-10 col-lg-7">

      <h2 class="text-center login-title"><%= t 'titles.pincode_form' %></h2>
      <div class="account-wall">

        <div class="form-signin">
          <%= form_tag('', method: 'post') do |f| %>

            <div class="field">
              <label for="pincode-field"><%= t('activerecord.attributes.event.pincode') %></label>
              <%= text_field_tag :pincode, params[:pincode], autofocus: true, class: 'form-control', type: "password", id: 'pincode-field' %>
            </div>

            <br />

            <div class="actions text-center">
              <button type="submit" class="btn btn-primary btn-lg btn-block"><%= t('button.confirm') %></button>
            </div>

          <% end %>
        </div>
      </div>

      <div class="text-center new-account">
        <%= link_to t('titles.to_the_main_page'), events_path %>
      </div>

    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="event">
  <div class="event-info row">
    <div class="col-md-12">
      <%= content_tag 'div', '', class: 'event-background',
        style: "background-image: url(#{event_photo(@event)})" %>

      <div class="event-info-inner row">
        <div class="col-md-6">
          <div class="event-description">
            <h1><%= @event.title %></h1>
            <h3><%= l @event.datetime, format: :short %></h3>

            <h3><small><%= link_to @event.address,
              "https://www.google.com/maps/place/#{@event.address}", target: :_blank, rel: "noopener noreferrer" %></small></h3>
            <p><%= @event.description %></p>
          </div>

          <% if policy(@event).edit? %>
            <div class="buffer-both">
              <%= link_to t('button.change'), edit_event_path(@event), class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <div class="google-div">
        <iframe class="google-maps" loading="lazy" allowfullscreen src="<%= "https://www.google.com/maps/embed/v1/place?q=#{@event.address}&key=#{ENV["GOOGLE_MAPS_API_KEY"]}" %>"></iframe>
      </div>

      <div class="event-photos">
        <div class="event-photos-gallery">
          <% if @event.photos.except(@new_photo).present? %>
            <h3><%= t('titles.all_event_photos') %></h3>
          <% end %>
          <div class="event-photos-gallery-uploaded">
            <%= render partial: 'photos/photo', collection: @event.photos.except(@new_photo) %>
          </div>
        </div>

        <div class="event-photo-form">
          <%= render partial: 'photos/form', locals: {photo: @new_photo || @event.photos.build} %>
        </div>
      </div>

      <div class="event-comments buffer-top">
        <%= render partial: 'comments/form',
          locals: {comment: @new_comment || @event.comments.build} %>

        <div class="buffer-both">
          <%= render partial: 'comments/comment',
            collection: @event.comments.except(@new_comment) %>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="event-owner">
        <h4><%= t('titles.invite_to_event') %></h4>
        <p><%= render partial: 'users/user', object: @event.user %></p>
      </div>
      <div class="event-subscriptions">
        <% if @event.subscriptions.except(@new_subscription).present? %>
          <h4><%= t('titles.current_followers') %></h4>
        <% end %>
        <div>
          <p>
          <%= render partial: 'subscriptions/subscription',
            collection: @event.subscriptions.except(@new_subscription) %>
          </p>
        </div>
      </div>
      <% unless current_user == @event.user %>
        <div class="event-subscription-form">
          <h4><%= t('titles.start_to_follow') %></h4>
          <div>
            <%= render partial: 'subscriptions/form', locals: {
              subscription: @new_subscription || @event.subscriptions.build } %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>